'use strict';

// Curated, bundled cat facts. Keep each entry one or two plain sentences.
module.exports = Object.freeze([
  'Cats spend roughly two thirds of their lives asleep, often 12 to 16 hours a day.',
  'A group of cats is called a clowder.',
  'A group of kittens is called a kindle.',
  'A male cat is called a tom, and an unspayed female is called a queen.',
  'Cats have 32 muscles in each ear, letting them swivel their ears independently.',
  'A cat can rotate its ears about 180 degrees.',
  'Cats can hear higher-pitched sounds than dogs or humans, up to around 64 kHz.',
  'A cat\'s nose print is unique, much like a human fingerprint.',
  'Cats have a third eyelid, called the nictitating membrane, that helps protect the eye.',
  'Cats need only about one sixth of the light humans need to see.',
  'A layer of tissue called the tapetum lucidum makes cats\' eyes shine in the dark.',
  'Cats see blues and greens but have trouble telling reds from greens.',
  'Adult cats have 30 teeth; kittens have 26 baby teeth.',
  'Cats cannot taste sweetness because they lack a working sweet taste receptor.',
  'A cat\'s rough tongue is covered in tiny backward-facing hooks called papillae.',
  'Cats walk like camels and giraffes, moving both right legs and then both left legs.',
  'Cats are digitigrade: they walk on their toes, not the soles of their feet.',
  'Most cats have five toes on each front paw and four on each back paw.',
  'Cats with extra toes are called polydactyl.',
  'Ernest Hemingway\'s home in Key West is still home to dozens of polydactyl cats.',
  'Cats have about 230 bones, more than the 206 in an adult human.',
  'A cat\'s collarbone is not attached to other bones, helping it squeeze through tight spaces.',
  'Cats can jump up to six times their body length in a single leap.',
  'The righting reflex lets a falling cat twist in midair to land on its feet.',
  'Kittens start to develop the righting reflex at around three to four weeks old.',
  'A domestic cat can sprint at about 30 miles per hour over short distances.',
  'Cats\' claws curve downward, which makes climbing down a tree head-first difficult.',
  'Cats scratch to mark territory, stretch their muscles and shed old claw sheaths.',
  'Cats have scent glands on their cheeks, paws and the base of their tail.',
  'When a cat rubs its face on you, it is marking you with its scent.',
  'A slow blink from a cat is a sign of trust, sometimes called a cat kiss.',
  'Adult cats rarely meow at each other; meowing is mostly for talking to humans.',
  'Kittens meow to get their mother\'s attention, and most cats outgrow it with other cats.',
  'Cats purr at a frequency of roughly 25 to 150 Hz.',
  'Cats purr when content, but also sometimes when stressed, hurt or giving birth.',
  'Scientists are still not certain exactly how cats produce a purr.',
  'Big cats that can roar, such as lions and tigers, generally cannot purr continuously.',
  'Cheetahs cannot roar, but they can purr.',
  'A cat\'s whiskers are roughly as wide as its body and help it judge tight gaps.',
  'Whiskers are called vibrissae and are packed with nerve endings.',
  'Cats have whiskers on the backs of their front legs, too.',
  'Cats usually have 12 whiskers on each side of the face, arranged in four rows.',
  'Cats are obligate carnivores and need nutrients, like taurine, found in animal tissue.',
  'Taurine deficiency can cause blindness and heart disease in cats.',
  'Many adult cats are lactose intolerant, so milk can upset their stomachs.',
  'Onions, garlic, grapes and lilies are toxic to cats.',
  'Even small amounts of lily pollen can cause kidney failure in cats.',
  'A cat\'s normal body temperature is about 38 to 39 °C (100.5 to 102.5 °F).',
  'A cat\'s heart beats about 140 to 220 times per minute.',
  'Cats sweat mainly through the pads of their paws.',
  'Cats spend up to half of their waking hours grooming themselves.',
  'Grooming helps cats regulate body temperature and spread natural skin oils.',
  'Hairballs form because cats swallow loose fur while grooming.',
  'Cats have a Jacobson\'s organ in the roof of the mouth for "tasting" scents.',
  'The open-mouthed grimace cats make when sniffing is called the flehmen response.',
  'A cat\'s sense of smell is roughly 14 times stronger than a human\'s.',
  'Catnip contains nepetalactone, a compound that triggers a playful response in many cats.',
  'Sensitivity to catnip is inherited; roughly a third of cats show no reaction.',
  'Kittens usually do not respond to catnip until they are a few months old.',
  'Silver vine and valerian root can excite some cats that ignore catnip.',
  'Cats were domesticated from the African wildcat, Felis lybica.',
  'Cats probably began living alongside humans around 10,000 years ago in the Near East.',
  'A cat was found buried with a human on Cyprus about 9,500 years ago.',
  'Ancient Egyptians revered cats and linked them with the goddess Bastet.',
  'Egyptians mummified many cats, and archaeologists have found them by the hundreds of thousands.',
  'Cats were kept on ships for centuries to control rats and mice.',
  'The domestic cat\'s scientific name is Felis catus.',
  'There are more than 70 recognized cat breeds, depending on the registry.',
  'Most orange tabby cats are male, because the orange gene sits on the X chromosome.',
  'Calico and tortoiseshell cats are almost always female.',
  'Male calico cats are rare and usually have an extra X chromosome.',
  'Tabby is a coat pattern, not a breed.',
  'Many tabby cats have a distinctive M-shaped marking on the forehead.',
  'Siamese cats have temperature-sensitive coat color, so their cooler extremities are darker.',
  'Siamese kittens are born almost entirely white and develop their points as they grow.',
  'White cats with blue eyes are more likely to be born deaf.',
  'Cats can have heterochromia, meaning each eye is a different color.',
  'All kittens are born with blue eyes; their adult eye color develops over several weeks.',
  'Kittens are born with their eyes closed and usually open them at 7 to 10 days old.',
  'Kittens are born deaf and their ear canals open at around two weeks old.',
  'A cat\'s pregnancy lasts about 63 to 65 days.',
  'A typical litter has three to five kittens.',
  'Kittens in the same litter can have different fathers.',
  'Female cats can become pregnant as early as four months old.',
  'The Maine Coon is one of the largest domestic cat breeds.',
  'The Sphynx looks hairless but is usually covered in fine, peach-fuzz down.',
  'Scottish Fold cats get their folded ears from a gene that also affects cartilage throughout the body.',
  'The Turkish Van is famous for enjoying water more than most cats.',
  'The average indoor cat lives about 12 to 18 years.',
  'Indoor cats generally live longer than cats allowed to roam outside.',
  'Creme Puff, a cat from Texas, lived to 38, according to Guinness World Records.',
  'Cats are crepuscular, meaning they are most active at dawn and dusk.',
  'Cats often bring prey to their owners, likely as a hunting behavior rather than a gift.',
  'A cat\'s tail held straight up usually signals a friendly greeting.',
  'A puffed-up tail means a cat is frightened or trying to look bigger.',
  'Kneading with the paws is a behavior kittens use while nursing and many adults keep.',
  'Cats show affection by head-butting, a behavior called bunting.',
  'Cats can recognize their owner\'s voice, even when they choose to ignore it.',
  'Studies show many cats can learn their own names.',
  'Cats often choose cardboard boxes because enclosed spaces make them feel safe.',
  'Cats have a wider field of view than humans, about 200 degrees.',
  'Cats struggle to see things right under their nose, so they rely on whiskers up close.',
  'Chirping or chattering at birds may be a sign of excitement or frustration.',
  'Isaac Newton is often credited with inventing the cat flap, though there is no firm evidence.',
  'The first cat show was held at the Crystal Palace in London in 1871.',
  'Félicette, a French cat, went to space in 1963 and returned safely.',
  'Larry, the Chief Mouser to the Cabinet Office, has lived at 10 Downing Street since 2011.',
  'Cats have been found in almost every country and on every continent except Antarctica.'
]);
